name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            # Client tests and coverage
            - name: Install Angular CLI
              run: npm install -g @angular/cli
              working-directory: client

            - name: Install client dependencies
              run: npm install
              working-directory: client

            - name: Run client tests
              working-directory: client
              run: ng test --configuration=ci --watch=false --browsers=ChromeHeadless

            - name: Check client coverage report
              working-directory: client
              run: |
                  if [ ! -f coverage/lcov.info ]; then
                    echo "Error: lcov.info not found"
                    exit 1
                  fi
                  cat coverage/lcov.info  # Display content for verification

            - name: Upload client coverage to Coveralls
              if: success() # Only upload coverage if previous steps were successful
              working-directory: client
              run: cat coverage/lcov.info | ./node_modules/.bin/coveralls
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

            # Server tests and coverage
            - name: Install server dependencies
              run: npm install
              working-directory: server

            - name: Run server tests
              working-directory: server
              run: npm test -- --coverage

            - name: Check server coverage report
              working-directory: server
              run: |
                  if [ ! -f coverage/lcov.info ]; then
                    echo "Error: lcov.info not found"
                    exit 1
                  fi
                  cat coverage/lcov.info  # Display content for verification

            - name: Upload server coverage to Coveralls
              if: success() # Only upload coverage if previous steps were successful
              working-directory: server
              run: cat coverage/lcov.info | ./node_modules/.bin/coveralls
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
